### ISSUE TITLE
[Feature Request] Structure Generation White/Blacklist

### ISSUE THREAD

**Issue by happybandit360** [FossilsArcheologyRevival/FossilsArcheologyRevival#1605] opened 2019-10-23 15:51 UTC
We are using the 1.12.2 version of Fossils and Archaeology Revival. We would love to see the ability to white and/or blacklist structure generation by dimension like you have with the ores. This would greatly extend our ability to integrate the mod more seamlessly into our pack.

**Comment by lindstheginj** [comment] 2020-04-01 06:54
Duplicate of newer #1646 . Just trying to condense the repeated issues.

**Closed by lindstheginj** 2020-04-01 06:54 UTC
