### ISSUE TITLE
Server Crash on version 8.0.1

### ISSUE THREAD

**Issue by River224** [FossilsArcheologyRevival/FossilsArcheologyRevival#1410] opened 2019-06-20 14:38 UTC
I am having the same issue myself. I am using version 8.0.1 with Forge 1.12.2 (14.23.5.2838) and llibrary-1.7.19-1.12.2.jar

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fossils and Archeology Revival (fossil)net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fossils and Archeology Revival (fossil)Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityList.func_192839_a(Ljava/lang/String;)Ljava/lang/Class; at fossilsarcheology.server.util.FoodMappings.addToEntityMappings(FoodMappings.java:399) at fossilsarcheology.server.util.FoodMappings.addMeatEntity(FoodMappings.java:593) at fossilsarcheology.server.util.FossilFoodMappings.register(FossilFoodMappings.java:161) at fossilsarcheology.server.ServerProxy.onPostInit(ServerProxy.java:225) at fossilsarcheology.Revival.onPostInit(Revival.java:93) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) at java.lang.Thread.run(Thread.java:748)

Sorry for text wall. i don't know how to set as a spoiler if it is possible.

**Comment by lindstheginj** [comment] 2019-06-20 15:02
Duplicate of #1358 
This issue has already been fixed; keep an eye out for 8.0.2. It will be released once we fix some other major bugs! For the mean time, please use 8.0.0 on your server.

**Closed by lindstheginj** 2019-06-20 15:02 UTC
