### ISSUE TITLE
Unplayable/main  screen cycling

### ISSUE THREAD

**Issue by Whitetigerdawn** [FossilsArcheologyRevival/FossilsArcheologyRevival#1311] opened 2019-04-09 23:00 UTC
Fossils and archeology added to a pack. When minecraft is loaded and sent to the main screen the fossils and archeology main screen picture cycles high speeds also makes the buttons unclickable.

**Comment by lindstheginj** [comment] 2019-06-19 22:42
Duplicate of #1094

**Closed by lindstheginj** 2019-06-19 22:42 UTC
