### ISSUE TITLE
Malnourished Dinosaurs

### ISSUE THREAD

**Issue by PartySwine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1552] opened 2019-09-29 04:08 UTC
Most Tamed Dinosaurs are starving to the point where they're dying. It seems fine with wild dinos so far, eating out of feeders. Tamed ones seem to decide not to eat out of feeders, or eat grass and other plants, and slowly die. Almost lost some birdies, crocs and brachis. May need to end them though...

**Comment by lindstheginj** [comment] 2019-09-29 04:22
Out of curiosity, were these dinosaurs that are starving tamed before you updated?

**Comment by PartySwine** [comment] 2019-09-29 04:28
Yes, they were tamed before the update.

**Comment by lindstheginj** [comment] 2019-10-13 04:53
Duplicate of #1562 
Closing this one even though it was first, bc the other issue provides more information.

**Closed by lindstheginj** 2019-10-13 04:53 UTC
