### ISSUE TITLE
Bug: "item.fossilseed_duisbergia.name" instead of the actual name of seed

### ISSUE THREAD

**Issue by MrWashingToad** [FossilsArcheologyRevival/FossilsArcheologyRevival#1514] opened 2019-08-29 00:27 UTC
![2019-08-28_17 01 46](https://user-images.githubusercontent.com/15614249/63901183-80565480-c9d1-11e9-8b2d-37df60800b7c.png)

Normal name not showing for the Duisbergia seeds.

**Comment by Gift-of-Names** [comment] 2019-08-29 01:51
Already fixed for 8.0.3, duplicate of #1482

**Closed** 2019-09-06 04:31 UTC
