### ISSUE TITLE
Mobs automatically start sitting when spawn into the world

### ISSUE THREAD

**Issue by BlobSnail** [FossilsArcheologyRevival/FossilsArcheologyRevival#425] opened 2016-07-18 17:06 UTC

**Comment by crakiMDH** [comment] 2016-07-18 22:03
I also have this issue. They said its to prevent them from growing up/going hungry. But I think they either didn't, or forgot to implement the code to make them stand up again :(

**Comment by PCAwesomeness** [comment] 2016-07-19 01:13
This is a duplicate of #421.

Someone close this, please.

**Closed** 2016-07-22 05:43 UTC
