### ISSUE TITLE
Doesn't work on my server

### ISSUE THREAD

**Issue by VBenedekN** [FossilsArcheologyRevival/FossilsArcheologyRevival#1386] opened 2019-06-11 08:32 UTC
I made a server with the mod and it crashes. When I remove the mod the server is working without any crash.

Version of the mod: 8.0.1

**Comment by ArkenorOakshadow** [comment] 2019-06-12 01:06
An issue for this bug is already open. https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1358

**Comment by lindstheginj** [comment] 2019-06-12 02:49
Duplicate of #1358

**Closed by lindstheginj** 2019-06-12 02:49 UTC
