### ISSUE TITLE
Analyzer some times doesn't work

### ISSUE THREAD

**Issue by TyrantrumGOD** [FossilsArcheologyRevival/FossilsArcheologyRevival#1392] opened 2019-06-13 18:30 UTC
There is a bug in 8.0.1 where the analyzer won't analyze a bio-fossil or any kind of fossil. It is going back to starting to analyze over and over again without giving something. The fossil stays where it is and takes a couple of tries to get it analyzed. Please fix this

**Comment by lindstheginj** [comment] 2019-06-14 01:19
Duplicate of #1379

**Closed by lindstheginj** 2019-06-14 01:19 UTC
