### ISSUE TITLE
Bugs with latest update

### ISSUE THREAD

**Issue by Xenoking** [FossilsArcheologyRevival/FossilsArcheologyRevival#1398] opened 2019-06-15 06:18 UTC
The analyzer, and cultivator are having massive problems that make it hard to even make dinosaurs. The analyzer takes forever to analyze fossils because it keeps on glitching with not analyzing anything for a while. The cultivator will make an egg or syringe and then later after an hour to get the dna it doesn't cultivate. Please fix these bugs soon!

**Comment by lindstheginj** [comment] 2019-06-19 20:54
Hey! In the future, make sure to label your bug reports with titles that describe the issue. "Bugs with latest update is very vague."
Also, this is a duplicate of #1360 , so I will redirect you there.

**Closed by lindstheginj** 2019-06-19 20:54 UTC
