### ISSUE TITLE
Growing different trees.

### ISSUE THREAD

**Issue by NatalTadPole** [FossilsArcheologyRevival/FossilsArcheologyRevival#1556] opened 2019-09-29 15:42 UTC
Hello dear F/A Revival team, I recently experienced a bug after the new update for 1.12.2 that the mod saplings when placed down and then grown with bonemeal would sometimes grow an entirely different tree. For example if I put down a palaeoraphe tree it would sometimes spawn a cordaites tree instead, or any of the other mod trees. I hope you found this information useful, otherwise if it were lacking information you can just email me.

**Comment by TropicalYeti** [comment] 2019-09-29 15:44
dupe of #1546

**Comment by Alex-the-666** [comment] 2019-09-29 18:00
fixed

**Closed by Alex-the-666** 2019-09-29 18:00 UTC
