### ISSUE TITLE
The Meganeura endlessly flies into a corner when enclosed in a room.

### ISSUE THREAD

**Issue by FlyGuy240** [FossilsArcheologyRevival/FossilsArcheologyRevival#1377] opened 2019-06-09 07:58 UTC
I built a relatively small exhibit for the dragon fly, and all it does is fly into the corner of the wall. always the same direction, never stops. 

If it helps, it flies South West always, when in a larger area it tends to fly around normally, but gets stuck very often. I forced it to stay, and just have it sitting down due to this issue.

**Comment by lindstheginj** [comment] 2019-06-12 02:52
Duplicate of #1364

**Closed by lindstheginj** 2019-06-12 02:52 UTC
