### ISSUE TITLE
Analyser and fossils not working correctly

### ISSUE THREAD

**Issue by RFAC** [FossilsArcheologyRevival/FossilsArcheologyRevival#1379] opened 2019-06-09 22:14 UTC
When biofossils and plant fossils are being  analysed they only disaper when they give DNA or seeds if they dont do that they will stay on the analyser and being analysed mutiple times until they give DNA

**Comment by Shuter892** [comment] 2019-06-10 12:28
I am having the same issue

**Comment by lindstheginj** [comment] 2019-06-14 01:40
Duplicate of #1360

**Closed by lindstheginj** 2019-06-14 01:40 UTC
