### ISSUE TITLE
Server Crash 8.0.1 

### ISSUE THREAD

**Issue by voidswrath** [FossilsArcheologyRevival/FossilsArcheologyRevival#1388] opened 2019-06-11 18:19 UTC
https://pastebin.com/Sd30yusH

**Comment by ArkenorOakshadow** [comment] 2019-06-12 01:05
An issue for this bug is already open. https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1358

**Comment by lindstheginj** [comment] 2019-06-12 02:50
Duplicate of #1358

**Closed by lindstheginj** 2019-06-12 02:50 UTC
