### ISSUE TITLE
Too many structures, spawning underwater and on top of trees

### ISSUE THREAD

**Issue by 0dinson** [FossilsArcheologyRevival/FossilsArcheologyRevival#1391] opened 2019-06-13 02:54 UTC
Spawn rates of buildings seem to be completely off, some buildings spawn so often they literally ruin any biome/landscape in terms of looks/immersion. 

Especially the aztec ones seem really off, worst of all is the spawn behavior though, they spawn underwater, on top of trees, the big maya temple spawns on small 5 block wide beaches etc. etc.. it just seems like everything just spawns everywhere it wants. 

Multiple archaeologist spawned underwater and also on top of trees. Until there is a severe fix to the huge issue with buildings I have to deactive every single one of them.

**Comment by lindstheginj** [comment] 2019-06-14 01:21
Duplicate of #1373 
Duplicate of #1387

**Closed by lindstheginj** 2019-06-14 01:21 UTC
