### ISSUE TITLE
Server crashes after i updated 

### ISSUE THREAD

**Issue by K-rexy0910** [FossilsArcheologyRevival/FossilsArcheologyRevival#1361] opened 2019-06-08 03:02 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/7/19 9:57 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fossils and Archeology Revival (fossil)
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityList.func_192839_a(Ljava/lang/String;)Ljava/lang/Class;
	at fossilsarcheology.server.util.FoodMappings.addToEntityMappings(FoodMappings.java:399)
	at fossilsarcheology.server.util.FoodMappings.addMeatEntity(FoodMappings.java:593)
	at fossilsarcheology.server.util.FossilFoodMappings.register(FossilFoodMappings.java:161)
	at fossilsarcheology.server.ServerProxy.onPostInit(ServerProxy.java:225)
	at fossilsarcheology.Revival.onPostInit(Revival.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3686453296 bytes (3515 MB) / 4152885248 bytes (3960 MB) up to 4152885248 bytes (3960 MB)
	JVM Flags: 3 total; -Xmx5G -Xms4G -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2811 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                            | Signature                                |
	|:----- |:------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft           | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJ | mcp                 | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJ | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2811-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge               | 14.23.5.2811      | forge-1.12.2-14.23.5.2811-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | micdoodlecore       |                   | minecraft.jar                                     | None                                     |
	| LCHIJ | securitycraft       | v1.8.10           | [1.12.2]+SecurityCraft+v1.8.10.jar                | None                                     |
	| LCHIJ | aether_legacy       | 1.12.2-v1.4.0     | aether_legacy-1.12.2-v1.4.0.jar                   | None                                     |
	| LCHIJ | biomesoplenty       | 7.0.1.2419        | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar     | None                                     |
	| LCHIJ | blockarmor          | 2.4.11            | BlockArmor-1.12.2-2.4.11.jar                      | None                                     |
	| LCHIJ | bookshelf           | 2.3.574           | Bookshelf-1.12.2-2.3.574.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | bullseye            | 3.0.7             | Bullseye-1.12.2-3.0.7.jar                         | None                                     |
	| LCHIJ | eplus               | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | llibrary            | 1.7.17            | llibrary-1.7.17-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIE | fossil              | 8.0.1             | fossilsarcheology-8.0.1.jar                       | None                                     |
	| LCHI  | cfm                 | 6.2.0             | furniture-6.2.0-1.12.2.jar                        | None                                     |
	| LCHI  | mantle              | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                          | None                                     |
	| LCHI  | jei                 | 4.14.4.264        | jei_1.12.2-4.14.4.264.jar                         | None                                     |
	| LCHI  | tconstruct          | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                  | None                                     |
	| LCHI  | galacticraftcore    | 4.0.2.190         | GalacticraftCore-1.12.2-4.0.2.190.jar             | None                                     |
	| LCHI  | galacticraftplanets | 4.0.2.190         | Galacticraft-Planets-1.12.2-4.0.2.190.jar         | None                                     |
	| LCHI  | gravestone          | 1.10.1            | gravestone-1.10.1.jar                             | None                                     |
	| LCHI  | ironchest           | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar                   | None                                     |
	| LCHI  | lumberjack          | 1.4.0             | lumberjack-1.4.0.jar                              | None                                     |
	| LCHI  | malisiscore         | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| LCHI  | malisisdoors        | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHI  | harvestcraft        | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zb.jar                   | None                                     |
	| LCHI  | veinminer           | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCHI  | veinminermodsupport | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCHI  | waystones           | 4.0.67            | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| LCHI  | worldedit           | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by K-rexy0910** [comment] 2019-06-08 03:03
I have several mods on the server as well.

**Comment by 4f6f3b** [comment] 2019-06-08 03:52
Duplicate of #1358

**Closed by 4f6f3b** 2019-06-08 03:52 UTC
