### ISSUE TITLE
Analyzers don't work

### ISSUE THREAD

**Issue by Stormexpedition** [FossilsArcheologyRevival/FossilsArcheologyRevival#1372] opened 2019-06-08 16:17 UTC
My analyzers can only analyze plant fossils but bio fossils,tar drops, and tar fossils can't be analyzed. Breaking and replacing down the block doesn't fix it and resetting the game doesn't fix it as well. Plants fossils now don't analyze as well now.

**Comment by starspunwolf** [comment] 2019-06-09 18:14
I've been having this issue as well.

**Comment by Stormexpedition** [comment] 2019-06-09 19:42
I have noticed that it has a small chance to actually analyze the fossil.

**Comment by lindstheginj** [comment] 2019-06-14 01:41
Duplicate of #1360

**Closed by lindstheginj** 2019-06-14 01:41 UTC
