### ISSUE TITLE
Raw fish texture in Meganeura nymph dinopedia entry is missing

### ISSUE THREAD

**Issue by CactusKingIII** [FossilsArcheologyRevival/FossilsArcheologyRevival#862] opened 2018-08-19 23:16 UTC
![2018-08-19_17 13 11](https://user-images.githubusercontent.com/42524078/44314227-8a637180-a3d3-11e8-932c-2810f6a049af.png)

**Comment by CactusKingIII** [comment] 2018-08-22 00:05
Upon further inspection it appears this happens with every Piscivore and Piscivore+Carnivore

**Comment by Alex-the-666** [comment] 2018-09-01 18:44
what other mods are you using

**Comment by CactusKingIII** [comment] 2018-09-01 21:00
Whatever was in the Pack, nothing else.

**Comment by Alex-the-666** [comment] 2018-09-29 16:49
wontfix, this is caused by pams food mod changing fish texture

**Closed by Alex-the-666** 2018-09-29 16:49 UTC
Labels: 1.12.2, bug
