### ISSUE TITLE
Game crashing server upon startup.

### ISSUE THREAD

**Issue by Dinusaur06** [FossilsArcheologyRevival/FossilsArcheologyRevival#1402] opened 2019-06-18 03:35 UTC
My server tends to crash every time I try to startup and it gives me an error from this mod. Just wondering if there's a fix or this is a bug. I'm using the latest 1.12.2 version (8.0.1) along with the latest llibary.
Heres the log:

Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present: llibrary (llibrary-core-1.0.11-1.12.2.jar) PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar) MekanismCoremod (Mekanism-1.12.2-9.7.7.378.jar) MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar) AstralCore (astralsorcery-1.12.2-1.10.19.jar) Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar) CTMCorePlugin (CTM-MC1.12.2-0.3.3.22 (1).jar) DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)Contact their authors BEFORE contacting forge
// Hi. I'm Minecraft, and I'm a crashaholic.
Time: 6/15/19 8:31 PMDescription: Exception in server tick loop
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fossils and Archeology Revival (fossil)Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityList.func_192839_a(Ljava/lang/String;)Ljava/lang/Class; at fossilsarcheology.server.util.FoodMappings.addToEntityMappings(FoodMappings.java:399) at fossilsarcheology.server.util.FoodMappings.addMeatEntity(FoodMappings.java:593) at fossilsarcheology.server.util.FossilFoodMappings.register(FossilFoodMappings.java:161) at fossilsarcheology.server.ServerProxy.onPostInit(ServerProxy.java:225) at fossilsarcheology.Revival.onPostInit(Revival.java:93) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) at java.lang.Thread.run(Thread.java:748)
A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.12.2 Operating System: Linux (amd64) version 4.9.120-xxxx-std-ipv6-64-hz1000 Java Version: 1.8.0_192, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 895446304 bytes (853 MB) / 2749366272 bytes (2622 MB) up to 2863661056 bytes (2731 MB) JVM Flags: 2 total; -Xmx3072M -Xms512M IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.5.2838 56 mods loaded, 56 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
| State | ID | Version | Source | Signature | |:----- |:------------------- |:-------------------- |:------------------------------------------------------ |:---------------------------------------- | | LCHIJ | minecraft | 1.12.2 | minecraft.jar | None | | LCHIJ | mcp | 9.42 | minecraft.jar | None | | LCHIJ | FML | 8.0.99.99 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJ | forge | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJ | micdoodlecore | | minecraft.jar | None | | LCHIJ | dsurroundcore | 3.5.4.3 | minecraft.jar | None | | LCHIJ | orbis-lib | 0.2.0 | orbis-lib-1.12.2-0.2.0+build42.jar | db341c083b1b8ce9160a769b569ef6737b3f4cdf | | LCHIJ | aether | 0.2.0 | aether_ii-1.12.2-0.2.0+build42-universal.jar | db341c083b1b8ce9160a769b569ef6737b3f4cdf | | LCHIJ | biomesoplenty | 7.0.1.2439 | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar | None | | LCHIJ | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None | | LCHIJ | jei | 4.15.0.268 | jei_1.12.2-4.15.0.268.jar | None | | LCHIJ | thaumcraft | 6.1.BETA26 | Thaumcraft-1.12.2-6.1.BETA26.jar | None | | LCHIJ | botania | r1.10-361 | Botania+r1.10-361 (1).jar | None | | LCHIJ | craftstudioapi | 1.0.0 | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None | | LCHIJ | mantle | 1.12-1.3.3.55 | Mantle-1.12-1.3.3.55.jar | None | | LCHIJ | natura | 1.12.2-4.3.2.69 | natura-1.12.2-4.3.2.69.jar | None | | LCHIJ | harvestcraft | 1.12.2zb | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None | | LCHIJ | twilightforest | 3.8.689 | twilightforest-1.12.2-3.8.689-universal.jar | None | | LCHIJ | animania | 1.6.2 | animania-1.12.2-1.6.2.jar | None | | LCHIJ | appliedenergistics2 | rv6-stable-6 | appliedenergistics2-rv6-stable-6 (1).jar | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 | | LCHIJ | astralsorcery | 1.10.19 | astralsorcery-1.12.2-1.10.19.jar | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 | | LCHIJ | backpack | 3.0.2 | backpack-3.0.2-1.12.2.jar | None | | LCHIJ | bibliocraft | 2.4.5 | BiblioCraft[v2.4.5][MC1.12.2].jar | None | | LCHIJ | codechickenlib | 3.2.2.353 | CodeChickenLib-1.12.2-3.2.2.353-universal (3).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 | | LCHIJ | redstoneflux | 2.0.1 | RedstoneFlux-1.12-2.0.1.2-universal.jar | d4f1503fbacd9b9fb767720420c5395104239ec9 | | LCHIJ | brandonscore | 2.4.12 | BrandonsCore-1.12.2-2.4.12.205-universal (1).jar | None | | LCHIJ | chisel | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35 (1).jar | None | | LCHIJ | chococraft | 0.9.1.52 | chococraft_1.12.1-0.9.1.52.jar | None | | LCHIJ | props | 2.6.2 | Decocraft-2.6.2_1.12.2.jar | None | | LCHIJ | draconicevolution | 2.3.22 | Draconic-Evolution-1.12.2-2.3.22.343-universal (1).jar | None | | LCHIJ | exoticbirds | 1.0 | Exotic+Birds+1.12.2-2.2.1.jar | None | | LCHIJ | tconstruct | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar | None | | LCHIJ | extrautils2 | 1.0 | extrautils2-1.12-1.9.9 (1).jar | None | | LCHIJ | familiarfauna | 1.0.11 | FamiliarFauna-1.12.2-1.0.11.jar | None | | LCHIJ | llibrary | 1.7.19 | llibrary-1.7.19-1.12.2 (1).jar | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec | | LCHIE | fossil | 8.0.1 | fossilsarcheology-8.0.1.jar | None | | LCHI | galacticraftcore | 4.0.2.210 | GalacticraftCore-1.12.2-4.0.2.210.jar | None | | LCHI | galacticraftplanets | 4.0.2.210 | Galacticraft-Planets-1.12.2-4.0.2.210.jar | None | | LCHI | ichunutil | 7.2.1 | iChunUtil-1.12.2-7.2.1.jar | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 | | LCHI | hats | 7.0.0 | Hats-1.12.2-7.0.2.jar | None | | LCHI | waila | 1.8.26 | Hwyla-1.8.26-B41_1.12.2.jar | None | | LCHI | inventorytweaks | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe | | LCHI | ironchest | 1.12.2-7.0.64.843 | ironchest-1.12.2-7.0.64.843.jar | None | | LCHI | journeymap | 1.12.2-5.5.4 | journeymap-1.12.2-5.5.4.jar | None | | LCHI | mca | 6.0.0-beta | MCA-1.12.2-6.0.0-beta-server-hotfix.jar | None | | LCHI | mekanism | 1.12.2-9.7.7.378 | Mekanism-1.12.2-9.7.7.378.jar | None | | LCHI | morph | 7.1.3 | Morph-1.12.2-7.1.3.jar | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 | | LCHI | mystcraft | 0.13.7.03 | mystcraft-1.12.2-0.13.7.03.jar | None | | LCHI | pixelmon | 7.0.6 | Pixelmon-1.12.2-7.0.6-universal.jar | None | | LCHI | roguelike | 1.8.0 | RoguelikeDungeons-1.12.2-1.8.0.jar | None | | LCHI | veinminer | 0.38.2 | VeinMiner-1.12-0.38.2.647+b31535a.jar | None | | LCHI | veinminermodsupport | 0.38.2 | VeinMiner-1.12-0.38.2.647+b31535a.jar | None | | LCHI | wawla | 2.5.273 | Wawla-1.12.2-2.5.273.jar | d476d1b22b218a10d845928d1665d45fce301b27 | | LCHI | phosphor-lighting | 1.12.2-0.2.4 | phosphor-1.12.2-0.2.4+build46-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 | | LCHI | orelib | 3.5.2.2 | OreLib-1.12.2-3.5.2.2.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a | | LCHI | dsurround | 3.5.4.3 | DynamicSurroundings-1.12.2-3.5.4.3.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar) net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcherPhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar) MekanismCoremod (Mekanism-1.12.2-9.7.7.378.jar) mekanism.coremod.KeybindingMigrationHelperMicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar) micdoodle8.mods.miccore.MicdoodleTransformerAstralCore (astralsorcery-1.12.2-1.10.19.jar) Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar) invtweaks.forge.asm.ContainerTransformerCTMCorePlugin (CTM-MC1.12.2-0.3.3.22 (1).jar) team.chisel.ctm.client.asm.CTMTransformerDynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar) org.orecruncher.dsurround.asm.Transformer Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced) - NaturaOverworld (Enabled/Not Forced) - NaturaNether (Enabled/Not Forced) - NaturaDecorative (Enabled/Not Forced) - NaturaTools (Enabled/Not Forced) - NaturaEntities (Enabled/Not Forced) - NaturaOredict (Enabled/Forced) - NaturaWorld (Enabled/Not Forced)
AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768 Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced) - TinkerWorld (Enabled/Not Forced) - TinkerTools (Enabled/Not Forced) - TinkerHarvestTools (Enabled/Forced) - TinkerMeleeWeapons (Enabled/Forced) - TinkerRangedWeapons (Enabled/Forced) - TinkerModifiers (Enabled/Forced) - TinkerSmeltery (Enabled/Not Forced) - TinkerGadgets (Enabled/Not Forced) - TinkerOredict (Enabled/Forced) - TinkerIntegration (Enabled/Forced) - TinkerFluids (Enabled/Forced) - TinkerMaterials (Enabled/Forced) - TinkerModelRegister (Enabled/Forced) - chiselIntegration (Enabled/Not Forced) - wailaIntegration (Enabled/Not Forced)
AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF Profiler Position: N/A (disabled) Is Modded: Definitely; Server brand changed to 'fml,forge' Type: Dedicated Server (map_server.txt)

**Comment by PlantDaddy** [comment] 2019-06-18 20:07
Hitting this same crash as well

**Comment by Gotyam** [comment] 2019-06-19 19:44
This is a dupe of [#1358](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1358), no?

**Comment by Emtech2** [comment] 2019-06-19 19:44
This is a known bug. No fix is currently available, you'll have to downgrade. #1358

**Comment by lindstheginj** [comment] 2019-06-19 20:49
Duplicate of #1358 
This issue has been fixed, we will have 8.0.2 released as soon as we can get some of the other major bugs squished!

**Closed by lindstheginj** 2019-06-19 20:49 UTC
